//
//  RootCoordinatable.swift
//  Scaffolding
//
//  Created by Alexandr Valíček on 26.09.2025.
//

import SwiftUI
import Observation

/// A coordinator that performs atomic root switches.
///
/// Conform to `RootCoordinatable` to build flows where the entire screen
/// content is swapped at once — for example, switching between
/// authentication and main-app coordinators. Provide a ``Root`` property
/// and define destination functions using the ``Scaffoldable()`` macro.
///
/// ```swift
/// @Scaffoldable @Observable
/// final class AppCoordinator: @MainActor RootCoordinatable {
///     var root = Root<AppCoordinator>(root: .login)
///
///     func login() -> any Coordinatable { LoginCoordinator() }
///     func main() -> any Coordinatable { MainTabCoordinator() }
/// }
/// ```
@available(iOS 17, macOS 14, *)
@MainActor
public protocol RootCoordinatable: Coordinatable where ViewType == RootCoordinatableView {
    /// The observable container that holds the current root destination.
    var root: Root<Self> { get }

    /// A type-erased accessor for the root container.
    var anyRoot: any AnyRoot { get }
}

@available(iOS 17, macOS 14, *)
@MainActor
public extension RootCoordinatable {
    var _dataId: ObjectIdentifier {
        root.id
    }

    var anyRoot: any AnyRoot {
        root.setup(for: self)
        return root
    }

    func view() -> RootCoordinatableView {
        root.setup(for: self)
        return .init(coordinator: self)
    }

    var parent: (any Coordinatable)? {
        root.parent
    }

    var hasLayerNavigationCoordinatable: Bool {
        root.hasLayerNavigationCoordinator
    }

    func setHasLayerNavigationCoordinatable(_ value: Bool) {
        root.hasLayerNavigationCoordinator = value
    }

    func setParent(_ parent: any Coordinatable) {
        root.setParent(parent)
    }

    /// Sets the default animation used for root transitions.
    func setRootTransitionAnimation(_ animation: Animation?) {
        root.setAnimation(animation: animation)
    }
}

@available(iOS 17, macOS 14, *)
@MainActor
public extension RootCoordinatable {
    /// Switches the root destination.
    ///
    /// - Parameters:
    ///   - destination: The new root destination.
    ///   - animation: An optional animation override. When `nil` the
    ///     container's default animation is used.
    /// - Returns: `self` for chaining.
    @discardableResult
    func setRoot(_ destination: Destinations, animation: Animation? = nil) -> Self {
        let dest = destination.value(for: self)

        dest.coordinatable?.setParent(self)
        root.setRoot(root: dest, animation: animation)

        return self
    }

    /// Switches the root destination and passes the resolved coordinator
    /// or view to a callback.
    ///
    /// - Parameters:
    ///   - destination: The new root destination.
    ///   - animation: An optional animation override.
    ///   - value: A closure that receives the resolved destination,
    ///     cast to `T`.
    /// - Returns: `self` for chaining.
    @discardableResult
    func setRoot<T>(
        _ destination: Destinations,
        animation: Animation? = nil,
        value: @escaping (T) -> Void
    ) -> Self {
        let dest = destination.value(for: self)

        dest.coordinatable?.setParent(self)
        root.setRoot(root: dest, animation: animation)

        if dest.coordinatable != nil, let coordinatable = dest.coordinatable as? T {
            value(coordinatable)
        } else if let view = dest.view as? T {
            value(view)
        } else {
            fatalError("Could not cast to type \(T.self)")
        }

        return self
    }

    /// Returns whether the current root matches the given destination.
    func isRoot(_ destination: Destinations.Meta) -> Bool {
        return root.root?.meta as! Self.Destinations.Meta == destination
    }
}

@available(iOS 17, macOS 14, *)
@MainActor
public extension RootCoordinatable {
    func setPresentedAs(_ type: PresentationType) {
        anyRoot.presentedAs = type
        if var root = anyRoot.root, root.pushType == nil {
            root.setPushType(type)
            anyRoot.root = root
        }
    }
}

/// The SwiftUI view generated by a ``RootCoordinatable`` coordinator.
///
/// You never create this view directly — call ``Coordinatable/view()``
/// on a `RootCoordinatable` coordinator to obtain it.
@available(iOS 17, macOS 14, *)
public struct RootCoordinatableView: CoordinatableView {
    private let _coordinator: any RootCoordinatable

    public var coordinator: any Coordinatable {
        _coordinator
    }

    init(coordinator: any RootCoordinatable) {
        self._coordinator = coordinator
    }

    @ViewBuilder
    func coordinatableView() -> some View {
        if let root = _coordinator.anyRoot.root {
            wrappedView(root)
                .environmentCoordinatable(coordinator)
                .id(_coordinator.anyRoot.root?.id)
        } else {
            EmptyView()
        }
    }

    public var body: some View {
        coordinator.customize(
            AnyView(
                coordinatableView()
            )
        )
        .environmentCoordinatable(coordinator)
    }
}
